name: sdlpop
title: SDLPoP
summary: Open Source Prince of Persia port.
description: |
  An open-source port of the 1989 "Prince of Persia" video game, based on the disassembly of the 
  DOS version.

  Controlling the kid:

    * left: turn or run left
    * right: turn or run right
    * up: jump or climb up
    * down: crouch or climb down
    * shift: pick up things
    * shift+left/right: careful step
    * shift while falling: grab onto ledge
    * home or up+left: jump left    
    * page up or up+right: jump right

  You can also use the numeric keypad.

  Gamepad equivalents:

  * D-Pad: arrows
  * Joystick: left/right
  * A: down
  * Y: up
  * X or triggers: shift
  * Start or Back: display in-game menu

  You can find more information and controls in the SDLPoP readme: <https://github.com/NagyD/SDLPoP/tree/master/doc>.

  This snap is maintained by the Snapcrafters community, and is not necessarily
  endorsed or officially maintained by the upstream developers.
license: "GPL-3.0"
adopt-info: sdlpop
grade: stable
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64

base: core22
confinement: strict

apps:
  sdlpop:
    extensions:
      - gnome
    command: prince
    command-chain:
      - bin/wrapper
    plugs:
      - opengl
      - audio-playback
      - screen-inhibit-control
      - joystick

parts:
  sdlpop:
    plugin: make
    source: https://github.com/NagyD/SDLPoP.git
    source-type: git
    source-subdir: src
    build-packages:
      - libsdl2-image-dev
    stage-packages:
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libsdl2-image-2.0-0
    override-pull: |
      craftctl default

      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag=v"$(snap info sdlpop | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      craftctl set version="$(git describe --tags | tr -d 'v')"
    override-build: |
      craftctl default
      cp -a * $CRAFT_PART_INSTALL/

    prime:
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-client.so.0.20.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-cursor.so.0.20.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-egl.so.1.20.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-server.so.0.20.0

  scripts:
    plugin: dump
    source: scripts
    organize:
      'wrapper': bin/wrapper

  cleanup:
    after: [sdlpop]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
